# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors', '0002_author_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='all_authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='books_authors.Author'),
        ),
    ]
